### ISSUE TITLE
需求！

### ISSUE THREAD

**Issue by tonyjiafan** [noahlam/main-frame#1]
主要想解决的业务场景是什么？

**Comment by noahlam** [comment]
类似浏览器的多页签，然后每个页签里面还可以任意跳转，避免 keep-alive, 有历史记录，可带查询参数，有一套统一的 API，等等，目前网上查到现有的同类框架页，我找到的都是只实现了多页签，其他功能都没实现的，所以就实现了这个，顺便开源出来，希望对别人有用。

**Comment by tonyjiafan** [comment]
👍
