### ISSUE TITLE
web pack 构建之后图片识别不到

### ISSUE THREAD

**Issue by 99565475** [noahlam/main-frame#10]
发布之后，图片不能识别

**Comment by edwinhuish** [comment]
估计是你的URL没有写对

**Comment by noahlam** [comment]
看看 webpack 的 rules 里面，对图片的处理路径跟你的目录有没有一致。

**Comment by 99565475** [comment]
多谢， 部署的时候少了一层目录




------------------ 原始邮件 ------------------
发件人: "Edwin Hui"<notifications@github.com>;
发送时间: 2019年6月1日(星期六) 凌晨0:54
收件人: "noahlam/vue-multi-tab"<vue-multi-tab@noreply.github.com>;
抄送: "Joson"<99565475@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [noahlam/vue-multi-tab] web pack 构建之后图片识别不到 (#10)




估计是你的URL没有写对
