### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by edwinhuish** [noahlam/main-frame#11]
1. 网址 # 后的特征码改为像vue-router那样的 url
2. 每次新增/关闭tab时，实时保存到 localstorage，避免误关闭导致的窗口丢失。
3. 限制Tab数量，可固定tab，以及加入可拖曳功能

**Comment by noahlam** [comment]
首先感谢你的建议。

这个特征码其实是 vue-router 的 url，只是我弄了个简单的加解密，防止用户信息暴露。也防止地址栏太难看。或许可以给个参数，让用户自己决定要不要加密，又或许，这些数据在地址栏显示本身就是个不太好的设计，放在其他地方也许更好。或许 2. 的内容就是第一点的一个解决方案，弄个映射表，把 url 的数据转存到 storage .

只是最近沉迷于工作上的业务，暂时无法自拔，稍后闲下来了，会继续完善。

大佬有没有兴趣贡献个 pr ?

**Comment by edwinhuish** [comment]
抱歉，暂时没有用到你的这个框架。另外，我不是大佬，只不过给你几点个人的建议。几年前有空的时候，做了一个jQuery的multi-tab，跟你这个类似。

代码有点渣，你可以看看功能。 [bootstrap-multitabs](https://github.com/edwinhuish/bootstrap-multitabs)

**Comment by edwinhuish** [comment]
之前我有将 tab 的 url 展示在地址栏的，后来做了自动保存tab状态的，为了安全起见，就隐藏了tab的url展示。

**Comment by noahlam** [comment]
感谢分享
