### ISSUE TITLE
请教多标签如何避免不同标签内的id，css, js 冲突？

### ISSUE THREAD

**Issue by edwinhuish** [noahlam/main-frame#2]
如题， 最主要是id冲突和JS冲突。

**Comment by noahlam** [comment]
样式冲突: vue 的 <style scoped> ?
js冲突:  webpack 不就是用来解决这个问题的？
id 冲突我不太明白是啥意思

**Comment by edwinhuish** [comment]
Tab标签能做成那样么？ vue 的 <style scoped> 和 webpack之所以能有用，主要是它并不会渲染页面以外的内容。

可是tab标签，无论多少个，都是共存在同一个页面的吧？也就是同一个```<html> ... </html>```之内。 难道也可以做成点击才渲染？然后及时销毁隐藏掉的tab？

抱歉，没有做过这样的实例。

**Comment by noahlam** [comment]
vue 的 scope 是按组件划分的，我的 tab 每个 tab 都是一个 组件。所以不会冲突。你不妨试一下哈。

**Comment by edwinhuish** [comment]
谢谢
