### ISSUE TITLE
hi，如果基于这个框架如何实现动态路由呢

### ISSUE THREAD

**Issue by guangzhou-huangbin** [noahlam/main-frame#3]
例如 router-link 的 addRouter 如何实现。

**Comment by noahlam** [comment]
这个具体我没有实践过，不过我想应该是能走的通的。
第一，你要动态的配置现有的 menu 项，这个简单，menu 本身只是一个数组，直接 push 即可。
第二，你可能还需要动态的去注册组件，这个也不难，具体的注册方法请看 `./src/Router/TabRoute.js`
