### ISSUE TITLE
npm run dev 后报错。

### ISSUE THREAD

**Issue by QinFeiFei** [noahlam/main-frame#4]
![tim 20181218103053](https://user-images.githubusercontent.com/19926579/50128536-5714ee80-02b0-11e9-9bf4-7fc47fc547c0.png)

**Comment by noahlam** [comment]
我刚刚运行了一遍，没重现你说的问题，这看起来似乎是 webpack-cli 的问题，不妨试试锁定如下依赖看看：
"webpack": "4.8.3",
"webpack-cli": "2.1.4",
"webpack-dev-server": "3.1.4"
